#!/bin/bash

#IF COMMAND IS USED TO TEST THE SUCCESSFULY EXECUTION OF COMMANDS PROVIDED BY BASH, BUT WE MAY NEED A SITUATION WHERE WE MAY NOT NEED TO RUN ANY COMMAND, RATHER WE NEED TO JUST CHECK HOW MANY PARAMETERS HAVE BEEN PASSEDOR TO EXECUTE ANY COMMAND ONCE THE SPECIFIED FILE HAS BEEN MENTIONED IN THE ARGUMENT THAT HAS BEEN PASSED, SO IN ORDER TO FULLFILL THIS REQUIREMENT THERE IS A NEED WHICH TESTS THE THE SITUATION AND ALLOWS THE IF STATEMENT TO EXECUTE A SERIES OF COMMANDS

echo -e "Enter the numeber from 1 to 10 \n"
read number

if test $number -lt 5
then
	echo -e "Number entered is less than 5 \n"
else
	if test $number -eq 5
	then
		echo -e "Number entered is equal to 5 \n"
	else
		echo -e "Number entered is greater than 5 \n"
	fi
fi
